export const countries = [
  { code: "+93", countryCode: "AF", name: "Afghanistan", level: 4 },
  { code: "+355", countryCode: "AL", name: "Albania", level: 4 },
  { code: "+213", countryCode: "DZ", name: "Algeria", level: 4 },
  { code: "+1684", countryCode: "AS", name: "American Samoa", level: 2 },
  { code: "+376", countryCode: "AD", name: "Andorra", level: 4 },
  { code: "+244", countryCode: "AO", name: "Angola", level: 4 },
  { code: "+1264", countryCode: "AI", name: "Anguilla", level: 2 },
  { code: "+672", countryCode: "AQ", name: "Antarctica", level: 2 },
  { code: "+1268", countryCode: "AG", name: "Antigua and Barbuda", level: 2 },
  { code: "+54", countryCode: "AR", name: "Argentina", level: 4 },
  { code: "+374", countryCode: "AM", name: "Armenia", level: 4 },
  { code: "+297", countryCode: "AW", name: "Aruba", level: 4 },
  { code: "+61", countryCode: "AU", name: "Australia", level: 2 },
  { code: "+43", countryCode: "AT", name: "Austria", level: 4 },
  { code: "+994", countryCode: "AZ", name: "Azerbaijan", level: 4 },
  { level: 0, name: "Azores", code: "+351" },
  { code: "+1242", countryCode: "BS", name: "Bahamas", level: 4 },
  { code: "+973", countryCode: "BH", name: "Bahrain", level: 4 },
  { code: "+880", countryCode: "BD", name: "Bangladesh", level: 4 },
  { code: "+1246", countryCode: "BB", name: "Barbados", level: 2 },
  { code: "+375", countryCode: "BY", name: "Belarus", level: 4 },
  { code: "+32", countryCode: "BE", name: "Belgium", level: 4 },
  { code: "+501", countryCode: "BZ", name: "Belize", level: 4 },
  { code: "+229", countryCode: "BJ", name: "Benin", level: 2 },
  { code: "+1441", countryCode: "BM", name: "Bermuda", level: 2 },
  { code: "+975", countryCode: "BT", name: "Bhutan", level: 4 },
  { code: "+591", countryCode: "BO", name: "Bolivia", level: 4 },
  { level: 4, name: "Bonaire", code: "+599" },
  { code: "+387", countryCode: "BA", name: "Bosnia and Herzegovina", level: 4 },
  { code: "+267", countryCode: "BW", name: "Botswana", level: 4 },
  { code: "+55", countryCode: "BR", name: "Brazil", level: 4 },
  {
    code: "+246",
    countryCode: "IO",
    name: "British Indian Ocean Territory",
    level: 0,
  },
  { level: 2, name: "British Virgin Islands", code: "+1" },
  { code: "+673", countryCode: "BN", name: "Brunei", level: 2 },
  { code: "+359", countryCode: "BG", name: "Bulgaria", level: 4 },
  { code: "+226", countryCode: "BF", name: "Burkina Faso", level: 4 },
  { level: 4, name: "Burma (Myanmar)", code: "+95" },
  { code: "+257", countryCode: "BI", name: "Burundi", level: 4 },
  { code: "+855", countryCode: "KH", name: "Cambodia", level: 2 },
  { code: "+237", countryCode: "CM", name: "Cameroon", level: 4 },
  { code: "+1", countryCode: "CA", name: "Canada", level: 4 },
  { level: 0, name: "Canary Islands", code: "+34" },
  { code: "+238", countryCode: "CV", name: "Cape Verde", level: 4 },
  { code: "+ 345", countryCode: "KY", name: "Cayman Islands", level: 2 },
  {
    code: "+236",
    countryCode: "CF",
    name: "Central African Republic",
    level: 4,
  },
  { code: "+235", countryCode: "TD", name: "Chad", level: 4 },
  { code: "+56", countryCode: "CL", name: "Chile", level: 4 },
  { code: "+86", countryCode: "CN", name: "China", level: 2 },
  { code: "+61", countryCode: "CX", name: "Christmas Island", level: 0 },
  { code: "+61", countryCode: "CC", name: "Cocos (Keeling) Islands", level: 0 },
  { code: "+57", countryCode: "CO", name: "Colombia", level: 4 },
  { code: "+269", countryCode: "KM", name: "Comoros", level: 4 },
  { code: "+242", countryCode: "CG", name: "Congo, Republic of the", level: 4 },
  { code: "+682", countryCode: "CK", name: "Cook Islands", level: 2 },
  { code: "+506", countryCode: "CR", name: "Costa Rica", level: 4 },
  { code: "+385", countryCode: "HR", name: "Croatia", level: 4 },
  { code: "+53", countryCode: "CU", name: "Cuba", level: 4 },
  { level: 4, name: "Curaçao", code: "+599" },
  { code: "+357", countryCode: "CY", name: "Cyprus", level: 4 },
  { code: "+420", countryCode: "CZ", name: "Czech Republic", level: 4 },
  {
    code: "+243",
    countryCode: "CD",
    name: "Democratic Republic of the Congo",
    level: 4,
  },
  { code: "+45", countryCode: "DK", name: "Denmark", level: 4 },
  { code: "+253", countryCode: "DJ", name: "Djibouti", level: 4 },
  { code: "+1767", countryCode: "DM", name: "Dominica", level: 2 },
  { code: "+1849", countryCode: "DO", name: "Dominican Republic", level: 4 },
  { level: 4, name: "Easter Island", code: "+56" },
  { code: "+593", countryCode: "EC", name: "Ecuador", level: 4 },
  { code: "+20", countryCode: "EG", name: "Egypt", level: 4 },
  { code: "+503", countryCode: "SV", name: "El Salvador", level: 4 },
  { code: "+240", countryCode: "GQ", name: "Equatorial Guinea", level: 4 },
  { code: "+291", countryCode: "ER", name: "Eritrea", level: 4 },
  { code: "+372", countryCode: "EE", name: "Estonia", level: 4 },
  { code: "+268", countryCode: "SZ", name: "Eswatini (Swaziland)", level: 4 },
  { code: "+251", countryCode: "ET", name: "Ethiopia", level: 4 },
  { level: 2, name: "Falkland Islands", code: "+500" },
  { code: "+298", countryCode: "FO", name: "Faroe Islands", level: 2 },
  { code: "+679", countryCode: "FJ", name: "Fiji", level: 2 },
  { code: "+358", countryCode: "FI", name: "Finland", level: 4 },
  { code: "+33", countryCode: "FR", name: "France", level: 4 },
  { code: "+594", countryCode: "GF", name: "French Guiana", level: 4 },
  { code: "+689", countryCode: "PF", name: "French Polynesia", level: 4 },
  { code: "+241", countryCode: "GA", name: "Gabon", level: 4 },
  { code: "+220", countryCode: "GM", name: "Gambia, The", level: 4 },
  { code: "+995", countryCode: "GE", name: "Georgia", level: 4 },
  { code: "+49", countryCode: "DE", name: "Germany", level: 4 },
  { code: "+233", countryCode: "GH", name: "Ghana", level: 4 },
  { code: "+350", countryCode: "GI", name: "Gibraltar", level: 4 },
  { code: "+30", countryCode: "GR", name: "Greece", level: 4 },
  { code: "+299", countryCode: "GL", name: "Greenland", level: 2 },
  { code: "+1473", countryCode: "GD", name: "Grenada", level: 2 },
  { code: "+590", countryCode: "GP", name: "Guadeloupe", level: 4 },
  { code: "+1671", countryCode: "GU", name: "Guam (U.S.)", level: 4 },
  { code: "+502", countryCode: "GT", name: "Guatemala", level: 4 },
  { code: "+44", countryCode: "GG", name: "Guernsey", level: 2 },
  { code: "+224", countryCode: "GN", name: "Guinea", level: 4 },
  { code: "+245", countryCode: "GW", name: "Guinea-Bissau", level: 4 },
  { code: "+592", countryCode: "GY", name: "Guyana", level: 4 },
  { code: "+509", countryCode: "HT", name: "Haiti", level: 4 },
  { code: "+504", countryCode: "HN", name: "Honduras", level: 4 },
  { code: "+852", countryCode: "HK", name: "Hong Kong SAR", level: 2 },
  { code: "+36", countryCode: "HU", name: "Hungary", level: 4 },
  { code: "+354", countryCode: "IS", name: "Iceland", level: 4 },
  { code: "+91", countryCode: "IN", name: "India", level: 4 },
  { code: "+62", countryCode: "ID", name: "Indonesia", level: 4 },
  { code: "+98", countryCode: "IR", name: "Iran", level: 4 },
  { code: "+964", countryCode: "IQ", name: "Iraq", level: 4 },
  { code: "+353", countryCode: "IE", name: "Ireland", level: 4 },
  { code: "+44", countryCode: "IM", name: "Isle of Man", level: 2 },
  { code: "+39", countryCode: "IT", name: "Italy", level: 4 },
  { code: "+225", countryCode: "CI", name: "Cote d'Ivoire", level: 2 },
  { code: "+1876", countryCode: "JM", name: "Jamaica", level: 4 },
  { code: "+81", countryCode: "JP", name: "Japan", level: 4 },
  { code: "+44", countryCode: "JE", name: "Jersey", level: 4 },
  { code: "+962", countryCode: "JO", name: "Jordan", level: 4 },
  { code: "+7", countryCode: "KZ", name: "Kazakhstan", level: 4 },
  { code: "+254", countryCode: "KE", name: "Kenya", level: 4 },
  { code: "+686", countryCode: "KI", name: "Kiribati", level: 2 },
  { code: "+383", countryCode: "XK", name: "Kosovo", level: 4 },
  { code: "+965", countryCode: "KW", name: "Kuwait", level: 4 },
  { code: "+996", countryCode: "KG", name: "Kyrgyzstan", level: 4 },
  { code: "+856", countryCode: "LA", name: "Laos", level: 2 },
  { code: "+371", countryCode: "LV", name: "Latvia", level: 4 },
  { code: "+961", countryCode: "LB", name: "Lebanon", level: 4 },
  { code: "+266", countryCode: "LS", name: "Lesotho", level: 4 },
  { code: "+231", countryCode: "LR", name: "Liberia", level: 4 },
  { code: "+218", countryCode: "LY", name: "Libya", level: 4 },
  { code: "+423", countryCode: "LI", name: "Liechtenstein", level: 4 },
  { code: "+370", countryCode: "LT", name: "Lithuania", level: 4 },
  { code: "+352", countryCode: "LU", name: "Luxembourg", level: 4 },
  { code: "+261", countryCode: "MG", name: "Madagascar", level: 4 },
  { code: "+265", countryCode: "MW", name: "Malawi", level: 4 },
  { code: "+60", countryCode: "MY", name: "Malaysia", level: 4 },
  { code: "+960", countryCode: "MV", name: "Maldives", level: 4 },
  { code: "+223", countryCode: "ML", name: "Mali", level: 4 },
  { code: "+356", countryCode: "MT", name: "Malta", level: 4 },
  { code: "+692", countryCode: "MH", name: "Marshall Islands", level: 2 },
  { code: "+596", countryCode: "MQ", name: "Martinique", level: 4 },
  { code: "+222", countryCode: "MR", name: "Mauritania", level: 4 },
  { code: "+230", countryCode: "MU", name: "Mauritius", level: 2 },
  { code: "+262", countryCode: "YT", name: "Mayotte", level: 4 },
  { code: "+52", countryCode: "MX", name: "Mexico", level: 4 },
  {
    code: "+691",
    countryCode: "FM",
    name: "Micronesia, Federated States of",
    level: 2,
  },
  { code: "+373", countryCode: "MD", name: "Moldova", level: 4 },
  { code: "+377", countryCode: "MC", name: "Monaco", level: 4 },
  { code: "+976", countryCode: "MN", name: "Mongolia", level: 2 },
  { code: "+382", countryCode: "ME", name: "Montenegro", level: 4 },
  { code: "+1664", countryCode: "MS", name: "Montserrat", level: 2 },
  { code: "+212", countryCode: "MA", name: "Morocco", level: 4 },
  { code: "+258", countryCode: "MZ", name: "Mozambique", level: 4 },
  { code: "+264", countryCode: "NA", name: "Namibia", level: 4 },
  { code: "+674", countryCode: "NR", name: "Nauru", level: 2 },
  { code: "+977", countryCode: "NP", name: "Nepal", level: 4 },
  { code: "+31", countryCode: "NL", name: "Netherlands, The", level: 4 },
  { code: "+687", countryCode: "NC", name: "New Caledonia", level: 2 },
  { code: "+64", countryCode: "NZ", name: "New Zealand", level: 2 },
  { code: "+505", countryCode: "NI", name: "Nicaragua", level: 4 },
  { code: "+227", countryCode: "NE", name: "Niger", level: 4 },
  { code: "+234", countryCode: "NG", name: "Nigeria", level: 4 },
  { code: "+683", countryCode: "NU", name: "Niue", level: 2 },
  { code: "+672", countryCode: "NF", name: "Norfolk Island", level: 0 },
  { code: "+850", countryCode: "KP", name: "North Korea", level: 4 },
  { level: 4, name: "North Macedonia", code: "+389" },
  {
    code: "+1670",
    countryCode: "MP",
    name: "Northern Mariana Islands",
    level: 2,
  },
  { code: "+47", countryCode: "NO", name: "Norway", level: 4 },
  { code: "+968", countryCode: "OM", name: "Oman", level: 4 },
  { code: "+92", countryCode: "PK", name: "Pakistan", level: 4 },
  { code: "+680", countryCode: "PW", name: "Palau", level: 2 },
  { code: "+507", countryCode: "PA", name: "Panama", level: 4 },
  { code: "+675", countryCode: "PG", name: "Papua New Guinea", level: 2 },
  { code: "+595", countryCode: "PY", name: "Paraguay", level: 4 },
  { code: "+51", countryCode: "PE", name: "Peru", level: 4 },
  { code: "+63", countryCode: "PH", name: "Philippines", level: 4 },
  { code: "+64", countryCode: "PN", name: "Pitcairn Islands (U.K.)", level: 4 },
  { code: "+48", countryCode: "PL", name: "Poland", level: 4 },
  { code: "+351", countryCode: "PT", name: "Portugal", level: 4 },
  { code: "+1939", countryCode: "PR", name: "Puerto Rico (U.S.)", level: 4 },
  { code: "+974", countryCode: "QA", name: "Qatar", level: 4 },
  { code: "+40", countryCode: "RO", name: "Romania", level: 4 },
  { code: "+7", countryCode: "RU", name: "Russia", level: 4 },
  { code: "+250", countryCode: "RW", name: "Rwanda", level: 2 },
  { level: 4, name: "Réunion", code: "+262" },
  { level: 2, name: "Saba", code: "+599" },
  { code: "+590", countryCode: "BL", name: "Saint Barthelemy", level: 2 },
  { code: "+290", countryCode: "SH", name: "Saint Helena", level: 2 },
  { code: "+1869", countryCode: "KN", name: "Saint Kitts and Nevis", level: 2 },
  { code: "+1758", countryCode: "LC", name: "Saint Lucia", level: 3 },
  { code: "+590", countryCode: "MF", name: "Saint Martin", level: 4 },
  {
    code: "+508",
    countryCode: "PM",
    name: "Saint Pierre and Miquelon",
    level: 2,
  },
  {
    code: "+1784",
    countryCode: "VC",
    name: "Saint Vincent and the Grenadines",
    level: 2,
  },
  { code: "+685", countryCode: "WS", name: "Samoa", level: 2 },
  { code: "+378", countryCode: "SM", name: "San Marino", level: 4 },
  { code: "+966", countryCode: "SA", name: "Saudi Arabia", level: 4 },
  { code: "+221", countryCode: "SN", name: "Senegal", level: 4 },
  { code: "+381", countryCode: "RS", name: "Serbia", level: 4 },
  { code: "+248", countryCode: "SC", name: "Seychelles", level: 2 },
  { code: "+232", countryCode: "SL", name: "Sierra Leone", level: 2 },
  { code: "+65", countryCode: "SG", name: "Singapore", level: 2 },
  { level: 2, name: "Sint Eustatius", code: "+599" },
  { level: 4, name: "Sint Maarten", code: "+599" },
  { code: "+421", countryCode: "SK", name: "Slovakia", level: 4 },
  { code: "+386", countryCode: "SI", name: "Slovenia", level: 4 },
  { code: "+677", countryCode: "SB", name: "Solomon Islands", level: 4 },
  { code: "+252", countryCode: "SO", name: "Somalia", level: 4 },
  { code: "+27", countryCode: "ZA", name: "South Africa", level: 4 },
  {
    code: "+500",
    countryCode: "GS",
    name: "South Georgia and the South Sandwich Islands",
    level: 0,
  },
  { code: "+82", countryCode: "KR", name: "South Korea", level: 2 },
  { code: "+211", countryCode: "SS", name: "South Sudan", level: 4 },
  { code: "+34", countryCode: "ES", name: "Spain", level: 4 },
  { code: "+94", countryCode: "LK", name: "Sri Lanka", level: 4 },
  { code: "+249", countryCode: "SD", name: "Sudan", level: 4 },
  { code: "+597", countryCode: "SR", name: "Suriname", level: 4 },
  { code: "+46", countryCode: "SE", name: "Sweden", level: 4 },
  { code: "+41", countryCode: "CH", name: "Switzerland", level: 4 },
  { code: "+963", countryCode: "SY", name: "Syria", level: 4 },
  { level: 4, name: "São Tomé and Príncipe", code: "+239" },
  { code: "+886", countryCode: "TW", name: "Taiwan", level: 2 },
  { code: "+992", countryCode: "TJ", name: "Tajikistan", level: 4 },
  { code: "+255", countryCode: "TZ", name: "Tanzania", level: 4 },
  { code: "+66", countryCode: "TH", name: "Thailand", level: 2 },
  {
    code: "+670",
    countryCode: "TL",
    name: "Timor-Leste (East Timor)",
    level: 2,
  },
  { code: "+228", countryCode: "TG", name: "Togo", level: 4 },
  { code: "+690", countryCode: "TK", name: "Tokelau", level: 2 },
  { code: "+676", countryCode: "TO", name: "Tonga", level: 2 },
  { code: "+1868", countryCode: "TT", name: "Trinidad and Tobago", level: 4 },
  { code: "+216", countryCode: "TN", name: "Tunisia", level: 4 },
  { code: "+90", countryCode: "TR", name: "Turkey", level: 4 },
  { code: "+993", countryCode: "TM", name: "Turkmenistan", level: 4 },
  {
    code: "+1649",
    countryCode: "TC",
    name: "Turks and Caicos Islands (U.K.)",
    level: 4,
  },
  { code: "+688", countryCode: "TV", name: "Tuvalu", level: 2 },
  { code: "+256", countryCode: "UG", name: "Uganda", level: 4 },
  { code: "+380", countryCode: "UA", name: "Ukraine", level: 4 },
  { code: "+971", countryCode: "AE", name: "United Arab Emirates", level: 4 },
  { code: "+1", countryCode: "US", name: "United States", level: 4 },
  { code: "+44", countryCode: "GB", name: "United Kingdom", level: 4 },
  { code: "+598", countryCode: "UY", name: "Uruguay", level: 2 },
  { code: "+998", countryCode: "UZ", name: "Uzbekistan", level: 4 },
  { code: "+678", countryCode: "VU", name: "Vanuatu", level: 2 },
  { code: "+58", countryCode: "VE", name: "Venezuela", level: 4 },
  { code: "+84", countryCode: "VN", name: "Vietnam", level: 2 },
  { code: "+1340", countryCode: "VI", name: "Virgin Islands, U.S", level: 4 },
  { level: 0, name: "Western Sahara", code: "+212" },
  { code: "+967", countryCode: "YE", name: "Yemen", level: 4 },
  { code: "+260", countryCode: "ZM", name: "Zambia", level: 4 },
  { code: "+263", countryCode: "ZW", name: "Zimbabwe", level: 4 },
]

export const civilStatus = [
  "Single",
  "Married",
  "Divorce",
  "Separated"
]

export const locations = [
  "New HQ",
  "Wilberforce",
  "Flagship",
  "Calaba Town",
  "Lungi",
  "Makeni",
  "Kono",
  "Kenema",
  "Bo"
]

export const levels = [
  "Chief Executive Office(CEO)",
  "Director",
  "Senior Manager",
  "Manager",
  "Assistant Manager ",
  "Senior Officer",
  "Officer",
]

export const types = [
  "Bussiness",
  "Home"
]

export const religions = [
  "Christianity",
  "Islam"
]

export const staffTypes = [
  "Pertime",
  "Full Time"
]

export const relationships = [
  "Son",
  "Daughter",
  "Husban",
  "Wife"
]

export const districts = [
  "Kailahun",
  "Kenema",
  "Kono",
  "Bo",
  "Bonthe",
  "Moyamba",
  "Pujehun",
  "Tonkolili",
  "Bombali",
  "Western Urban",
  "Western Rural",
  "Portloko",
  "Karene",
  "Falaba",
  "Koinadugu",
  "Kambia"
];

export const studentTypes = [
  "Regular",
  "Grant-In-Aid"
]